@include "c:\\util\\gawk\\PaGawkLib.awk"
BEGIN {
  FS = "," ;
  OFS = ";" ;
  fOut="test.csv" ;
  tAdr[0]="00 Vingtmillade octet 1" ;
  tAdr[1]="01 Vingtmillade octet 2" ;
  tAdr[2]="02 Vingtmillade octet 3" ;
  tAdr[3]="03 QuatreVingtade" ;
  tAdr[4]="04 ?" ;
  tAdr[5]="05 Approche" ;
  tAdr[6]="06 Approche, DAC tracking doubleur" ;
  tAdr[7]="07 ?" ;
  tAdr[8]="08 Analogique pas de 0,1dB et 1dB" ;
  tAdr[9]="09 Analogique BCD modulation b01" ;
  tAdr[10]="10 Analogique BCD modulation b11" ;
  tAdr[11]="11 Analogique Correction FM" ;
  tAdr[12]="12 FM" ;
  tAdr[13]="13 Diviseur incréments" ;
  tAdr[14]="14 ?" ;
  tAdr[15]="15 ?" ;
}


# ; CSV, generated by libsigrok4DSL 0.2.0 on Sun Nov 05 15:33:50 2023
# ; Channels (13/16)
# ; Sample rate: 1 MHz
# ; Sample count: 2.896 M Samples
# Time(s), D0, D1, D2, D3, D4, D5, D6, D7, A0, A1, A2, A3, Chargt
# 0,0,0,0,0,0,0,0,0,1,1,1,1,1
# 0.095445,0,0,0,0,0,0,0,0,0,1,0,1,1
# 0.095456,0,0,0,0,0,0,0,0,0,1,0,0,1
# 0.095472,0,0,0,0,0,0,0,0,0,1,1,0,1

BEGINFILE {
  fileBase=FILENAME ;
  sub(/^.*[\\\\\/]/,"",fileBase) ;
  fOut="Out/Dec_" fileBase ;
  haveChargt=0 ;
  chargtOld=0 ;
}

FNR>5 {
  tm=$1 ;
  d0=$2 ; d1=$3 ; d2=$4 ; d3=$5 ; d4=$6 ; d5=$7 ; d6=$8 ; d7=$9 ;
  data = d0 + d1*2 + d2*4 + d3*8 + d4*16 + d5*32 + d6*64 + d7*128 ;
  libData = d7 d6 d5 d4 d3 d2 d1 d0 ;
  a0=$10 ; a1=$11 ; a2=$12 ; a3=$13 ;
  adr = a0 + a1*2 + a2*4 + a3*8 ;
  if( adr+0 in tAdr )
    libAdr=a3 a2 a1 a0 " " tAdr[adr] ;
  else
    libAdr=adr " Err. adresse." ;
  chargt=$14+0 ;
  # The CSV contains one row for every logic-state change.  A bus write is
  # valid only on the falling edge of Chargt, not for every row where the
  # signal happens to be low.
  if( haveChargt && chargtOld==1 && chargt==0 )
  {
    print sprintf("%0.8f", tm),libData " " libAdr, data > fOut ;
  }
  chargtOld=chargt ;
  haveChargt=1 ;
}

END {
  if( fOut!="" )
    close(fOut) ;
}
